#!/usr/bin/env python3
"""Generates a .env file for Docker Compose from legion.ports definitions."""

import os
import sys

# Adjust path to import legion.ports
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, PROJECT_ROOT)

try:
    # Assuming legion.ports is the unified way to get port configurations
    from legion import ports as unified_port_manager
except ImportError as e:
    print(f"Error importing legion.ports: {e}. Check PYTHONPATH.", file=sys.stderr)
    sys.exit(1)


def generate_env_file(output_path=".env.docker-compose"):
    # Define the mapping from service_key in legion.ports.DEFAULT_PORTS
    # to desired .env variable names for Docker Compose.
    # Keys here should match those in legion.ports.DEFAULT_PORTS
    port_mappings = {
        "web": "WEB_UI_PORT",  # For the existing web service in docker-compose, maps to its internal port
        "dev_frontend": "PORT_ALLOCATOR_DEV_FRONTEND",  # Used directly in docker-compose.yml
        "chroma": "CHROMA_PORT",
        "prometheus": "PROMETHEUS_PORT",
        "redis": "REDIS_PORT",
        "postgres": "POSTGRES_PORT",
        "grafana": "GRAFANA_PORT",
        "orchestrator": "ORCHESTRATOR_PORT",  # Example if orchestrator itself is dockerized or needs exposure
        # Add other services from DEFAULT_PORTS as needed for Docker env
    }

    # Ensure the output path is absolute or relative to project root for consistency
    if not os.path.isabs(output_path) and PROJECT_ROOT not in output_path:
        abs_output_path = os.path.join(PROJECT_ROOT, output_path)
    else:
        abs_output_path = output_path

    # Ensure legion.ports.RUNTIME_PORTS is loaded (it should be on import, but explicit call is safer)
    unified_port_manager.load_runtime_ports()

    with open(abs_output_path, "w") as f:
        f.write("# This file is auto-generated by scripts/generate_docker_env.py\n")
        f.write("# It uses port definitions from legion/ports.py and .env.ports.\n")
        f.write("# Do not edit manually. Your changes will be overwritten.\n\n")
        for service_key, env_var_name in port_mappings.items():
            port = unified_port_manager.get_port(service_key)
            if port is not None:
                f.write(f"{env_var_name}={port}\n")
            else:
                print(
                    f"Warning: Port for '{service_key}' not found. {env_var_name} will not be set in {abs_output_path}.",
                    file=sys.stderr,
                )

    print(f"Generated Docker environment file at {abs_output_path}")


if __name__ == "__main__":
    default_env_filename = ".env.docker-compose"
    # Determine output file path, prioritizing command-line argument
    if len(sys.argv) > 1:
        custom_path = sys.argv[1]
        if os.path.isdir(custom_path):
            output_file = os.path.join(custom_path, default_env_filename)
        elif (
            os.path.sep not in custom_path and not os.path.splitext(custom_path)[1]
        ):  # No path separator, no extension
            # Assume it's a directory name under project root
            output_file = os.path.join(PROJECT_ROOT, custom_path, default_env_filename)
        else:  # Treat as a full path or a filename in project root
            if not os.path.isabs(custom_path):
                output_file = os.path.join(PROJECT_ROOT, custom_path)
            else:
                output_file = custom_path
    else:
        output_file = os.path.join(PROJECT_ROOT, default_env_filename)

    generate_env_file(output_file)
