[mypy]
mypy_path = .
python_version = 3.10
explicit_package_bases = True
namespace_packages = True
plugins = sqlalchemy.ext.mypy.plugin
ignore_missing_imports = True
exclude = tests/middleware/.*_stub\.py$

[mypy-tests.*]
ignore_errors = true

[mypy-core.db.models]
disable_error_code = misc

[mypy-memory.db.models]
disable_error_code = misc
