"""Initial migration stub."""

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("Applying migration 0001 (stub)")
    # Example: Create a dummy table
    # op.create_table('example_table',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=50), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("Reverting migration 0001 (stub)")
    # Example: Drop the dummy table
    # op.drop_table('example_table')
    pass
    # ### end Alembic commands ###
