"""Remove orphaned tables to align with current models

Revision ID: 23d69e6237ea
Revises: 20250521_conversation_directive
Create Date: 2025-05-24 09:04:32.056639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '23d69e6237ea'
down_revision = '20250521_conversation_directive'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_registry')
    op.drop_index('ix_conversations_thread_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('directives')
    op.drop_table('task_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('agent_name', sa.TEXT(), nullable=True),
    sa.Column('task_data', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directives',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), nullable=False),
    sa.Column('agent_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_thread_id', 'conversations', ['thread_id'], unique=1)
    op.create_table('task_registry',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('tags', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('owner', sa.VARCHAR(), nullable=False),
    sa.Column('agent', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
